#! /bin/bash

dir_origin=$PWD

cd /etc/nginx/sites-enabled/
ln -s /volume/server/django_project

cp /volume/server/pg_hba.conf /etc/postgresql/14/main/

service nginx restart
service postgresql restart

cd /volume/server/SQL
psql -U postgres -a -f createUser.sql
psql -U postgres -a -f createDatabase.sql
psql -U postgres -a -f createTableExercises.sql
psql -U postgres -a -f createTableTags.sql
psql -U postgres -a -f createTableMessages.sql
psql -U postgres -a -f updateTableAuthUser.sql
psql -U postgres -a -f createTableErrors.sql 

cd /volume/backend/
python3 manage.py makemigrations
python3 manage.py migrate

# gunicorn -c /volume/conf/gunicorn_config.py django_project.wsgi &

service nginx restart
service postgresql restart

cd $dir_origin
