#! /bin/bash

cd /etc/nginx/sites-enabled/
ln -s /volume/conf/django_project

cp /volume/conf/pg_hba.conf /etc/postgresql/14/main/

service nginx start
service postgresql start

cd /volume/temp/
psql -U postgres -a -f createUser.sql
psql -U postgres -a -f createDatabase.sql

cd /volume/
virtualenv venv
. venv/bin/activate
pip3 install django psycopg2 gunicorn

cd /volume/django_project/
python3 manage.py makemigrations
python3 manage.py migrate

cd /volume/temp/
psql -U postgres -a -f createChalanges.sql
psql -U postgres -a -f createTableTags.sql
psql -U postgres -a -f updateTableAuthUser.sql

gunicorn -c /volume/conf/gunicorn_config.py django_project.wsgi &

service restart nginx
service restart postgresql

lsof -i :8000

cd /volume/temp
